import { Header } from '@/widgets/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from '@/config/providers/Providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="ru">
			<head></head>
			<body>
				<div className='app-js-group' >
					<Providers>
						<Header />
						<main className={inter.className}>
							{children}
						</main>
					</Providers>
				</div>
			</body>
		</html>
	)
}
