'use client'
import { Header } from '@/widgets/Header'
import '@styles/index.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from '@/config/providers/Providers'
import { Footer } from '@/widgets/Footer'
import './../shared/i18n'
import { usePathname } from 'next/navigation'
import { HeaderMain } from '@/widgets/HeaderMainPage'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Iot-travel',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {

	const pathname = usePathname()
	return (
		<html lang="ru">
			<head></head>
			<body>
				<div className='app-js-group' >
					<Providers>
						{/* <Header /> */}
						{pathname == '/' ? <HeaderMain /> : <Header />}

						<main className={inter.className}>
							{children}
						</main>
						<Footer />
					</Providers>
				</div>
			</body>
		</html>
	)
}
